# fly.toml app configuration file generated for los-pibe-whip on 2026-07-29T16:36:02-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'los-pibe-whip'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[[services]]
  protocol = 'tcp'
  internal_port = 8889

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 30

[[services]]
  protocol = 'udp'
  internal_port = 9000

  [[services.ports]]
    port = 9000

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
